// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA38QywU0y0M-lUg9wQlrfsWiowBhKsACI',
    appId: '1:724748021154:web:5e460209a230057107d6fb',
    messagingSenderId: '724748021154',
    projectId: 'plant-120d1',
    authDomain: 'plant-120d1.firebaseapp.com',
    storageBucket: 'plant-120d1.appspot.com',
    measurementId: 'G-Q5Y0K6EP49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2VQBubEs3-O7mSlZKfGdERm-mqZHuo5Y',
    appId: '1:724748021154:android:2ebb7baedf4501ec07d6fb',
    messagingSenderId: '724748021154',
    projectId: 'plant-120d1',
    storageBucket: 'plant-120d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMDU7ewPcIML9CeTWO-H-S4jaeGUTuRnY',
    appId: '1:724748021154:ios:04d6b1af65e05b9c07d6fb',
    messagingSenderId: '724748021154',
    projectId: 'plant-120d1',
    storageBucket: 'plant-120d1.appspot.com',
    iosBundleId: 'com.example.plantapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMDU7ewPcIML9CeTWO-H-S4jaeGUTuRnY',
    appId: '1:724748021154:ios:3a0f235a785b041807d6fb',
    messagingSenderId: '724748021154',
    projectId: 'plant-120d1',
    storageBucket: 'plant-120d1.appspot.com',
    iosBundleId: 'com.example.plantapp.RunnerTests',
  );
}
